import { ArtifactIndexPage } from "@/components/artifacts/ArtifactIndexPage";
import { listPdfArtifacts } from "@/lib/artifacts";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "PDF export artifacts",
};

export default async function PdfArtifactListPage() {
  const items = await listPdfArtifacts();

  return (
    <ArtifactIndexPage
      title="PDF export artifacts"
      description="Available PDF exports generated by the local Pi export tooling."
      kind="pdf"
      items={items}
      emptyTitle="No PDF exports found"
      emptyDescription="Export a PDF and it will appear here."
    />
  );
}
