import { ArtifactIndexPage } from "@/components/artifacts/ArtifactIndexPage";
import { listRenderArtifacts } from "@/lib/artifacts";

export const dynamic = "force-dynamic";

export const metadata = {
  title: "HTML render artifacts",
};

export default async function RenderArtifactListPage() {
  const items = await listRenderArtifacts();

  return (
    <ArtifactIndexPage
      title="HTML render artifacts"
      description="Available MDX render pages generated by the local Pi render tooling."
      kind="render"
      items={items}
      emptyTitle="No render artifacts found"
      emptyDescription="Generate an HTML render and it will appear here."
    />
  );
}
